### ISSUE TITLE
Support deployment as a Google Cloud Function

### ISSUE THREAD

**Issue by kieras** [kieras/zombie-projects-watcher#50]
Also, add a scheduler to trigger the function.
Deployment using Terraform scripts.

**Comment by kieras** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Zombies] - Make it work as a Cloud Function (w/ Chats group)](https://trello.com/c/KQzQaCk6/68-zombies-make-it-work-as-a-cloud-function-w-chats-group)

**Comment by andersonj-cit** [comment]
Deployed as a function on the PR #[63](https://github.com/kieras/zombie-projects-watcher/pull/63)
